name: Android Unit Tests

on: [push, pull_request]

jobs:
  test:
    name: Linux Android Unit Tests
    runs-on: self-hosted

    steps:
      - run: touch starting_test_actionscheckout@v1_11
      - uses: actions/checkout@v1
      - run: touch starting_test_actionssetup-java@v1_12
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: touch starting_test_subositoflutter-action@v1_15
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.4'
      - run: touch starting_test_flutterdoctor_18
      - run: flutter doctor
      - run: touch starting_test_flutterpubget_19
      - run: flutter pub get
      - run: touch starting_test_shandroid_test.sh_20
      - run: sh android_test.sh 

